create table category (category_id bigint not null auto_increment, category_name varchar(255) not null, primary key (category_id)) engine=InnoDB;
create table event (event_date DATETIME(0) not null, event_id bigint not null auto_increment, owner_id bigint not null, maps_url varchar(1000) not null, description varchar(3000) not null, place varchar(255) not null, title varchar(255) not null, primary key (event_id)) engine=InnoDB;
create table event_categories (category_id bigint not null, event_id bigint not null, primary key (category_id, event_id)) engine=InnoDB;
create table message (date DATETIME(0) not null, event_id bigint not null, id bigint not null auto_increment, user_id bigint not null, message varchar(3000) not null, primary key (id)) engine=InnoDB;
create table notification (event_id bigint, notification_id bigint not null auto_increment, user_id bigint, message varchar(1000), primary key (notification_id)) engine=InnoDB;
create table participant_list (event_id bigint not null, user_id bigint not null, primary key (event_id, user_id)) engine=InnoDB;
create table picture (event_id bigint, picture_id bigint not null auto_increment, uri varchar(255) not null, primary key (picture_id)) engine=InnoDB;
create table role (role_id bigint not null auto_increment, role_name varchar(255) not null, primary key (role_id)) engine=InnoDB;
create table roles_list (role_id bigint not null, user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table user (blocked bit, date_of_birth date not null, enabled bit, logged_out bit, user_id bigint not null auto_increment, first_name varchar(64) not null, last_name varchar(64) not null, password_code varchar(64), upload_code varchar(64), verification_code varchar(64), email varchar(255) not null, profile_picture varchar(255) not null, primary key (user_id)) engine=InnoDB;
create table user_credential (user_id bigint not null, username varchar(32) not null, password varchar(255) not null, primary key (user_id)) engine=InnoDB;
alter table category add constraint UK_lroeo5fvfdeg4hpicn4lw7x9b unique (category_name);
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user_credential add constraint UK_6s3isow7rby7lajiubl6rcxkv unique (username);
alter table event add constraint FKpukp8q71te29sy099ik1kv9c6 foreign key (owner_id) references user (user_id);
alter table event_categories add constraint FK2dq8ncb5bdr61iu8wkcou3pd3 foreign key (category_id) references category (category_id);
alter table event_categories add constraint FKg0l4lu4fo069a5tefj56q3l12 foreign key (event_id) references event (event_id);
alter table message add constraint FKn49j1k5pgk4e0h71etqxc0r4g foreign key (event_id) references event (event_id);
alter table message add constraint FKb3y6etti1cfougkdr0qiiemgv foreign key (user_id) references user (user_id);
alter table notification add constraint FKb0yvoep4h4k92ipon31wmdf7e foreign key (user_id) references user (user_id);
alter table participant_list add constraint FK1t0v6m8gmpop2y8mqxpjnh4w6 foreign key (event_id) references event (event_id);
alter table participant_list add constraint FKpvc8hjr2tt7mq4c80x8bjyc54 foreign key (user_id) references user (user_id);
alter table picture add constraint FK3gwkuy88ivddsvkp0grx7is9g foreign key (event_id) references event (event_id);
alter table roles_list add constraint FK9nr5cb6575balhuuvtte95ea3 foreign key (role_id) references role (role_id);
alter table roles_list add constraint FKgl081902bxw072dd33b092kx9 foreign key (user_id) references user (user_id);
alter table user_credential add constraint FKdutodhqsg596mb3kq9l9ofw9q foreign key (user_id) references user (user_id);
insert into role(role_name) values ('ADMIN'), ('USER');
insert into category(category_name) values ('sport'), ('cinema'), ('culture'), ('art'), ('convention'), ('workshop'), ('food');
insert into category(category_name) values ('school'), ('coding'), ('tech'), ('show'), ('exhibition'), ('concert'), ('festival');
insert into category(category_name) values ('fundraiser'), ('videogames'), ('table games'), ('press conference'), ('press day'), ('fair'), ('karaoke');
insert into category(category_name) values ('football'), ('soccer'), ('rugby'), ('baseball'), ('basket'), ('boxe'), ('tennis');
insert into category(category_name) values ('swimming'), ('karate'), ('hockey'), ('marathon'), ('skiing'), ('cricket'), ('tournament');
insert into category(category_name) values ('competition'), ('exciting'), ('premiere'), ('celebrities'), ('film'), ('museum'), ('conference');
insert into category(category_name) values ('wine'), ('gastronomy'), ('education'), ('music'), ('entertainment'), ('live performance'), ('gala');
insert into category(category_name) values ('charity'), ('philantropy'), ('gaming'), ('fun'), ('technology'), ('innovation'), ('media');
insert into category(category_name) values ('news'), ('announcement'), ('championship'), ('literature'), ('book'), ('nightlife'), ('match');
insert into category(category_name) values ('game'), ('event'), ('philanthropy');
